server {
    listen 80;
    listen [::]:80;
    server_name max_click_pesh.iteacher-alex.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 503;
    }
}
